### PR TITLE
Auto-merge demo

### PR DESCRIPTION
**Pull request by kkjeer**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #0000
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by kkjeer** [comment]
@msft-github-bot only wait 1 minute before merging

**Comment by dzearing** [comment]
@msft-github-bot tell me a joke

**Comment by kkjeer** [comment]
@msft-github-bot require at least 2 approvals

**Comment by kkjeer** [comment]
@msft-github-bot make sure either @disuser or @cliffkoh approves

**Comment by kkjeer** [comment]
@msft-github-bot only require one approval

**Pull request merged**
